# Generated by Django 2.0.1 on 2018-01-16 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0013_auto_20180113_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contents', models.TextField(help_text='seperate each item by comma')),
                ('excludes', models.TextField(blank=True, help_text='seperate each item by comma', null=True)),
                ('public', models.BooleanField(default=True)),
                ('restaurant',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.RestaurantLocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
